from dictionary import *
from uber import *
#lugar=("H3","dire")
#lugar2=("2", "diree")
#load_fix_element(lugar)
#load_fix_element(lugar2)
#printHashTable(H_Ubi_Fija)
ubimovil=("P2","direccion", 125)
ubimovil2=("c1", "direcccion",268)
ubimovil3=("p2","direee", 365)
load_movil_element(ubimovil)
load_movil_element(ubimovil2)
load_movil_element(ubimovil3)
printHashTable(H_Personas)
print("--------------------j-----------")
printHashTable(H_Autos)